title: The Bad Monkey Dev
email: michaelkelly322@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm an entrepreneur/engineer, husband, and father. I build APIs, launch side-projects, and work on engines (both digital and mecahnical)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thebadmonkeydev.github.io" # the base hostname & protocol for your site
twitter_username: thebadmonkeydev
github_username:  thebadmonkeydev

# Build settings
markdown: kramdown
theme: minima
encoding: utf-8
gems:
  - jekyll-coffeescript
